---

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Copy config file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 0644
  notify: restart dnsmasq

- name: Configure dsnmasq to start at boot
  service: name=dnsmasq enabled=yes state=started

- meta: flush_handlers
